language: node_js
sudo: false
dist: trusty
node_js:
  - "8"
matrix:
  fast_finish: true
script:
    - npm install && npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
notifications:
    email:
        on_success: never
