language: javascript
sudo: false
dist: trusty
node_js:
  - "stable"
matrix:
  fast_finish: true
before_install:
    - npm install yarn -g
# do not send success notifications, they have no value
script:
    - yarn build
notifications:
    email:
        on_success: never
